"""empty message

Revision ID: 3bfa8500104e
Revises: 
Create Date: 2022-06-15 11:44:33.897218

"""
from alembic import op
import sqlalchemy as sa
from app.models import CfgParameters


# revision identifiers, used by Alembic.
revision = '3bfa8500104e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfg_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('material_cost', sa.Integer(), nullable=False),
    sa.Column('material_density', sa.Float(), nullable=False),
    sa.Column('spool_weigth', sa.Integer(), nullable=False),
    sa.Column('electric_cost', sa.Float(), nullable=False),
    sa.Column('printer_power', sa.Float(), nullable=False),
    sa.Column('printer_price', sa.Float(), nullable=False),
    sa.Column('amortization_years', sa.Integer(), nullable=False),
    sa.Column('daily_printer_time', sa.Float(), nullable=False),
    sa.Column('failure_rate_prcent', sa.Float(), nullable=False),
    sa.Column('workforce_cost', sa.Float(), nullable=False),
    sa.Column('measure_unit', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_name')
    )
    op.create_index(op.f('ix_cfg_parameters_id'), 'cfg_parameters', ['id'], unique=False)
    # ### end Alembic commands ###
    op.bulk_insert(CfgParameters.__table__, [
        {   'id': 1,
            'profile_name': 'Default',
            'material_cost': 70000,
            'material_density': 1.24,
            'spool_weigth': 100,
            'electric_cost': 450,
            'printer_power': 300,
            'printer_price': 1300000,
            'amortization_years': 2,
            'daily_printer_time': 4,
            'failure_rate_prcent': 10,
            'workforce_cost': 10000,
            'measure_unit': True
        }
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cfg_parameters_id'), table_name='cfg_parameters')
    op.drop_table('cfg_parameters')
    # ### end Alembic commands ###


